### ISSUE TITLE
consider img2xterm

### ISSUE THREAD

**Issue by haarp** [kfei/sshcam#1]
[img2xterm](https://github.com/rossy/img2xterm) might be worth considering for colored output

**Comment by kfei** [comment]
@haarp 
Awesome! I'll definitely digging into that project!

**Comment by denilsonsa** [comment]
Funny, I came here exactly to suggest [img2xterm](https://github.com/rossy/img2xterm), but for a different purpose: [img2xterm uses Unicode LOWER HALF BLOCK (▄ U+2584)](https://github.com/rossy/img2xterm/blob/master/img2xterm.c#L206) as a way to duplicate the vertical resolution, which will also make the "pixels" look less tall and more square-ish.

**Comment by kfei** [comment]
@denilsonsa 
Thanks for coming. Using the half block characters from Unicode is definitely a good idea, I'll give it a try! But the behaviour on a terminal which does not support Unicode should be cared also. This makes me kind of confused. Will a SSH client send its encoding compatibilities to server?

**Comment by denilsonsa** [comment]
Unlikely, but you can look at the locale variables to try to detect if UTF-8 is enabled/available.

Personally, I think you could just add a command-line flag to disable UTF-8 if the user wants. We're already in 2014, UTF-8 terminals are the norm.

**Comment by kfei** [comment]
Closing this issue by:
- d70b2a1012f0a715385c2f7623237bb3df243b07 increased vertical resolution by using Unicode 'HALF BLOCK' characters.
- 07cd74f4d850fb83fc686c1f7e238393eefd61af added color support by the _img2xterm_ package (I re-implemented in Go).

@haarp , @denilsonsa Thanks to both of you! :)
